baseURL = '/'
languageCode = 'en-us'
title = 'Scott Stolarski Portfolio'
theme = 'hugo-theme-shell'


[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Jane Doe's Portfolio!"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "Scott"
  pcName = "laptop"
  workDir = "my_portfolio"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  terminalDelay = 5  

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  activityDelay = 1

  description = """
  Hey,

  Thank you for visiting my portfolio! 

  If you have any questions, please send me an email
  at csstolarski@gmail.com

  - Scott Stolarski
  
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "projects"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["Go_Plant", "/projects/"],
  ]

[Params.Site]
  use = true
  folderName = "Links"
  files = [ 
    ["Github", "https://github.com/Stolarskis"],
    ["LinkedIn", "https://www.linkedin.com/in/christopher-stolarski/"],
    ["Resume.pdf", "/resume/"],
    ["Snails_Eating_Cucumbers.mov", "https://www.youtube.com/watch?v=vq_LPys54qU"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
